### ISSUE TITLE
Add support for MF289F

### ISSUE THREAD

**Issue by stich86** [4IceG/luci-app-3ginfo-lite#10]
Hi @4IceG 

i'm porting OpenWRT on MF289F. This is a "little" brother of MF286D.
ID of modem are the same

`Bus 002 Device 002: ID 19d2:1485 ZTE,Incorporated ZTE Mobile Broadband`

But the one into this router is 4CA, so the command "AT+ZCAINFO?" reporting 4 bands instead of 3 if you are forcing bands or leaving it in AUTO.

Here is an example output:

`at+zcainfo?
+ZCAINFO: 298, 20, 33003, 6400, 10.0;          130, 2, 3, 1850, 20.0;          225, 2, 1, 525, 15.0;          16, 2, 7, 3025, 15.0;
`

Do you think that is possible to add 4th band display, making a check on ATI commands? I've seen your script, should be easy to address.

Are you going to add also 3rd and 4th band on the LuCI UI? Currently only 2nd is displayed

Thanks :)

**Comment by 4IceG** [comment]
Hi @stich86 
I was supposed to change 3ginfo, because they already wrote to me on the forum that it could show more, but I don't know how to show it yet, so that it would be still simple.

Scripts are just scripts and we can customize them, change them to show more (more bands).

**Comment by stich86** [comment]
> Hi @stich86 I was supposed to change 3ginfo, because they already wrote to me on the forum that it could show more, but I don't know how to show it yet, so that it would be still simple.
> 
> Scripts are just scripts and we can customize them, change them to show more (more bands).

i've sent you a PR, here is how is loking with the other bands added:

![image](https://user-images.githubusercontent.com/27808541/182877540-b5a11fd8-980d-4157-800c-ff26d8201e3f.png)

let me know if you like it :)

**Comment by 4IceG** [comment]
Hi @stich86 , it's cool that you've customized the scripts, but I won't add it as is anyway because I've already modified 3ginfo and it's similar but different (I'll show in a picture later what it looks like). I'm not publishing the changes because I'm still thinking of an elegant way to search for BTS by Cell ID.

**Comment by 4IceG** [comment]
Hi @stich86 
I have published a new version of the package, you can take a peek to see if it looks better.

**Comment by stich86** [comment]
looks like mine with the addon of BTS info. Problem of that MF289F doesn't give cell-id into AT+CREG command :(

Now we have a problem with MF289F AT2 rev that expose modem as MF286\286A. The script of MF286\286A is using into AWK field seprator that doesn't contain ";", so all paramerts are wrong.

As you have implemented isn't easy to fix, because you are looking VID\PID thru usb devices..

Any ideas?

**Comment by 4IceG** [comment]
if the "modems are the same", maybe you need to do device name verification? and depend on the name of the script?

**Comment by stich86** [comment]
> if the "modems are the same", maybe you need to do device name verification? and depend on the name of the script?

yes are the same, but the HW rev AT2 expose it as 19d2:1432 instead of 19d2:1485, so you script will use addon "19d21432" that doesn't recognize the output of AT commands

**Comment by 4IceG** [comment]
So the script should verify which device it is running on, since the modems are the same, you need to add the device name condition.

**Comment by stich86** [comment]
> So the script should verify which device it is running on, since the modems are the same, you need to add the device name condition.

yes.. an may be the idea is to parametrize the AWK filter based on device name, so you will avoid to replicate all band stuff on the script

What do you think?

**Comment by 4IceG** [comment]
There is no other way, since the script should be universal.

**Comment by stich86** [comment]
> There is no other way, since the script should be universal.

ok i'll try to refactor your script and send a PR so you can check if can be integrated

**Comment by stich86** [comment]
PR create, take a look and let me know :)

**Comment by 4IceG** [comment]
Okay, it looks unusual, but if it works. Today I'm barely alive after work so tomorrow I'll add it and make a test package. I don't have this router so the guys on the forum will have to check if it works.

**Comment by stich86** [comment]
MiG25 has that modem on Eko, so he can also test it.

I've already tested on a router of a friend and it's working
