### ISSUE TITLE
luci-app-3ginfo-lite apk package compile fails

### ISSUE THREAD

**Issue by Jalakas** [4IceG/luci-app-3ginfo-lite#103]
luci-app-3ginfo-lite **apk** package compile fails:

> make[3] -C feeds/luci3ginfolite/luci-app-3ginfo-lite compile
> ERROR: info field 'version' has invalid value: package version is invalid
> ERROR: failed to create package: ../openwrt/bin/packages/mips_24kc/luci3ginfolite/luci-app-3ginfo-lite-1.0.74-20240827-r1.apk: package version is invalid

I believe apk versions does not like dash in version, as here:
https://github.com/openwrt/packages/commit/bc14a5428b66e0a191417a47fb8a78884c8b607a

**Comment by 4IceG** [comment]
Hi @Jalakas ,
I fixed Makefile to be compatible with the apk.
