### ISSUE TITLE
CSS support?

### ISSUE THREAD

**Issue by bam80** [4IceG/luci-app-3ginfo-lite#16]
Hi, thank you for the project.
I'm not very familiar with Web technologies, but I see no CSS in the languages list:
![image](https://user-images.githubusercontent.com/233979/190981731-75eb4ee5-a1c1-41d8-94db-2c0baec9973d.png)

Do you think it can be added?

**Comment by 4IceG** [comment]
Hi @bam80 ,
CSS file is not required, the package is based on the standard LuCI appearance, if something needs to be changed dynamically js script does it and that's it. The package was supposed to look simple.

**Comment by bam80** [comment]
OK.
It's just because I asked some modification from alternative project:
https://github.com/koshev-msk/modemfeed/tree/master/luci/applications/luci-app-modeminfo
and I was replied the visual change I wanted is a job for CSS.

Ideally, I would like the interface something like this, for pointing antenna on roof :)
![image](https://user-images.githubusercontent.com/233979/191085262-2a0a27d4-9240-4b7e-bdc3-c53a10bb2676.png)

**Comment by 4IceG** [comment]
My package does not go into space :), I do not need so much data, and not every modem provides that much.
