### ISSUE TITLE
suggestion: constant IPK filename for stable URL to the latest release?

### ISSUE THREAD

**Issue by bam80** [4IceG/luci-app-3ginfo-lite#17]
> #Package installation example
Latest version ➜ https://github.com/4IceG/luci-app-3ginfo-lite/releases/latest

It's not easy currently to install latest version of the app from within a script.

The reason is there is no constant Github URL to latest IPK file released - you can find a whole thread dedicated to such problem:
https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8
On of the solution suggested is to use static names for the release artifacts:
https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8?permalink_comment_id=3936277#gistcomment-3936277

Could we use that?

**Comment by 4IceG** [comment]
Hi @bam80 , ok no problem. The new update will be in a new format.
