### ISSUE TITLE
Permission denied at opkg install

### ISSUE THREAD

**Issue by erdoukki** [4IceG/luci-app-3ginfo-lite#2]
```
Configuring luci-app-3ginfo-lite.
//usr/lib/opkg/info/luci-app-3ginfo-lite.postinst: /usr/lib/opkg/info/luci-app-3ginfo-lite.postinst-pkg: line 4: /usr/share/3ginfo-lite/set_3ginfo_port.sh: Permission denied
uci: Entry not found
```

**Comment by erdoukki** [comment]
the scripts need executable flags...
May be the Makefile is missing a install section with INSTALLBIN...

**Comment by 4IceG** [comment]
Thank you for reporting. I know the error is occuring but I haven't found an effective way to fix it.

**Comment by erdoukki** [comment]
fixed by setting the permissions **before** building the package (may be a bug in luci packaging ?)
