### ISSUE TITLE
update for Telit Ln940 (QMI)/Telit Ln940 (MBIM)/HP lt4220 (MBIM)/HP lt4220 (QMI)

### ISSUE THREAD

**Issue by odie84** [4IceG/luci-app-3ginfo-lite#20]
[luci-app-3ginfo-lite-main.zip](https://github.com/4IceG/luci-app-3ginfo-lite/files/9693112/luci-app-3ginfo-lite-main.zip)
![gambar](https://user-images.githubusercontent.com/32309857/193468032-1f8d9fb1-534b-4924-87c2-951e923cef29.png)
![gambar](https://user-images.githubusercontent.com/32309857/193468057-8d7fce75-bab6-47eb-813e-a91b6d81df28.png)

**Comment by 4IceG** [comment]
I added missing data. For me, the plus sign separates the main band from the aggregation bands.
