### ISSUE TITLE
idea: publish built packages on GitLab Pages

### ISSUE THREAD

**Issue by bam80** [4IceG/luci-app-3ginfo-lite#21]
Right now the packages are published as GitHub's Assets:
https://github.com/4IceG/luci-app-3ginfo-lite/releases
IIUC, the drawback of it is they can't be accessible as HTTP directory to be served as OpenWrt package repository, thus this offering is not well suited for it's main use-cases: installing on router with `opkg` and embedding into the firmware with ImageBuilder.

I don't know if it could be solved within GitHub infrastructure somehow, but it seems like GitLab has a solution:
> With [GitLab Pages](https://docs.gitlab.com/ee/user/project/pages/index.html), you can publish static websites directly from a repository in GitLab.

So we could setup an CI/CD pipeline building a packages on GitLab and have them available on OpenWrt package repository served via GitLab Pages.

**Comment by 4IceG** [comment]
I was planning to add a new tab to download / update a package from github from LuCI (using Curl and wget).

Making additional repositories in my opinion does not make sense for the three packages.
