### ISSUE TITLE
Please add for lede project

### ISSUE THREAD

**Issue by mrkenz9595** [4IceG/luci-app-3ginfo-lite#24]
I can't use for [https://github.com/coolsnowwolf/lede](Lede Project). Please support it, because my device is not support by openwrt officiall. Many thank.

**Comment by 4IceG** [comment]
Lede is very old so I won't back down. What kind of modem is it? Maybe usually 3ginfo would handle it.

**Comment by mrkenz9595** [comment]
Thank for reply. Modem is support, but device not support. Menu 3ginfo not show in tab sevices for lede, I check function show in the source code that use lua. No menu.d and js.

**Comment by 4IceG** [comment]
The old 3ginfo is just scripts, doesn't require compilation, so you can install the package and then fix the LUA files, I think it should work.
