### ISSUE TITLE
I want to add download and upload files like this, how do I do that?

### ISSUE THREAD

**Issue by odie84** [4IceG/luci-app-3ginfo-lite#29]
![Screenshot_1](https://user-images.githubusercontent.com/32309857/209443864-3d547eaf-2c02-4f0c-8449-169cfd170baa.png)

**Comment by 4IceG** [comment]
Hi, you show me a package that provides a lot of data, so what do you want to add when you see everything. My package is unnecessary since you are using a better tool.
