### ISSUE TITLE
Add support for Quectel RM520N-GL

### ISSUE THREAD

**Issue by lrdrdn** [4IceG/luci-app-3ginfo-lite#34]
Please add support [luci-app-3ginfo-lite](https://github.com/4IceG/luci-app-3ginfo-lite) & [luci-app-modemband](https://github.com/4IceG/luci-app-modemband)

Quectel RM520N-GL
vid:pid  `2c7c:0801`

All command same as Quectel RG502Q-EA 
serial port `/dev/ttyUSB3`
Supported band:
```
at+qnwprefcfg="lte_band"
+QNWPREFCFG: "lte_band",1:2:3:4:5:7:8:12:13:14:17:18:19:20:25:26:28:29:30:32:34:38:39:40:41:42:43:48:66:71
```

**Comment by 4IceG** [comment]
Hi @lrdrdn 
If it's the same, I'll add the modem in the next package release.

**Comment by lrdrdn** [comment]
I copied file 2c7c0800 to 2c7c0801, but  modem type & protocol not display properly.

![image](https://user-images.githubusercontent.com/93698387/213914856-0245923e-6bbc-46db-b314-ba6be691e636.png)

**Comment by 4IceG** [comment]
Commands similar, but scripts need fixing anyway. Ok, I will write here when I add the modem.

**Comment by 4IceG** [comment]
Hi @lrdrdn , replace with this file and see if it will be better.
[2c7c0801.zip](https://github.com/4IceG/luci-app-3ginfo-lite/files/10479763/2c7c0801.zip)

**Comment by lrdrdn** [comment]
working correctly
![image](https://user-images.githubusercontent.com/93698387/214045894-30ae4315-25eb-48cb-9661-e84372065b9e.png)

**Comment by 4IceG** [comment]
The modem is already added to 3ginfo-lite, with the compilation I am waiting for the update of the modemband package by Cezary.

**Comment by pedroo84** [comment]
Hello guys, recently I got a RM520N-GL, but it is locked to "mbim" this way I can't access the AT commands to change it to ECM, any idea how can I do this? in order to have read outs on 3g-info?

**Comment by 4IceG** [comment]
Hi @pedroo84 , I don't know in the end if you want to use mbim or ecm modem. My modem works in mbim and I'm not complaining. Do you have the kmod-usb-serial kmod-usb-serial-option packages installed?

**Comment by pedroo84** [comment]
> Hi @pedroo84 , I don't know in the end if you want to use mbim or ecm modem. My modem works in mbim and I'm not complaining. Do you have the kmod-usb-serial kmod-usb-serial-option packages installed?

Hi Rafal, actually mbim works with modem manager here too, the problem is that the USBtty port won't show up on my modem, therefore I can't access AT Command and also 3G-Info can't read the data too. Do you think my module needs a firmware update to solve this? 

I own other Quectel modems and never encountered such issue.

**Comment by 4IceG** [comment]
First of all, uninstall modem manager. Then check if you have the required packages listed above. Finally, set the modem to work in mbim and configure the connection. Important! my packages don't work with MM.
