### ISSUE TITLE
EP06-E json issue

### ISSUE THREAD

**Issue by GektorUA** [4IceG/luci-app-3ginfo-lite#40]
![image](https://user-images.githubusercontent.com/33571352/220138833-7889edea-30ee-4725-9e4b-e79b13f69870.png)

**Comment by 4IceG** [comment]
Hi @GektorUA , thanks for reporting. Extract and replace this file in a folder
`/usr/share/3ginfo-lite/3ginfo-addon/`
It should be ok now.
[2c7c0306.zip](https://github.com/4IceG/luci-app-3ginfo-lite/files/10787211/2c7c0306.zip)

**Comment by 4IceG** [comment]
I checked the scripts on the EM160R-GL and it was ok, so the modem must be returning something unusual.

@GektorUA show the result of the command
`sh -x /usr/share/3ginfo-lite/3ginfo.sh`

**Comment by 4IceG** [comment]
It's possible this is causing the error. Probably the modem is roaming and the commands return unusual data.

**Comment by 4IceG** [comment]
It's hard for me to say now, it could probably be fixed.

We need the result of the scripts at the time of the error.
A terribly problematic modem, constantly need to fix something in the scripts.

The package is simple, it sends at commands to the modem and cuts the necessary data giving the result in the form of json. It is enough that the modem returns something that is not described and the json structure is damaged = errors in LuCI.

**Comment by 4IceG** [comment]
> Modem is very stable, it one of the best modems for industrial segment.

I didn't write that the modem is bad. I meant it just requires more patience 😉.
Ok, so I'll go back to the version you provided.
