### ISSUE TITLE
add scripts

### ISSUE THREAD

**Issue by odie84** [4IceG/luci-app-3ginfo-lite#44]
asking for help to add the script

https://github.com/koshev-msk/modemfeed/blob/master/luci/applications/luci-app-modeminfo/luasrc/view/modem/modeminfo.htm

![frequency band calculator](https://github.com/4IceG/luci-app-3ginfo-lite/assets/32309857/8f259449-af64-4633-87fe-6a1472ef674d)

**Comment by 4IceG** [comment]
Hi @odie84 ,
You wrote very little information, I don't know where to add? why add?

**Comment by odie84** [comment]
> Hi @odie84 , You wrote very little information, I don't know where to add? why add?

i want to add this information in luci-app-3ginfo-lite.
![modeminfo1](https://github.com/4IceG/luci-app-3ginfo-lite/assets/32309857/02ecadd5-d295-4a3e-a4a2-8351ef3485b0)

the information is very useful and every 4G modem should be useful.

**Comment by 4IceG** [comment]
I don't see where or why it makes sense to add this data, in case 3ginfo-lite is already showing frequencies showing bands.

I have repeated more than once that I do not want to add excess information so that the package does not lose its readability.

**Comment by odie84** [comment]
[3ginfo-lite.zip](https://github.com/4IceG/luci-app-3ginfo-lite/files/12548176/3ginfo-lite.zip)

Solve.

![gambar](https://github.com/4IceG/luci-app-3ginfo-lite/assets/32309857/2e5e8f13-e929-4030-ad56-667ab4f3da2c)


![gambar](https://github.com/4IceG/luci-app-3ginfo-lite/assets/32309857/0efc3864-658e-4ef8-abd4-0798ae39fcab)


![gambar](https://github.com/4IceG/luci-app-3ginfo-lite/assets/32309857/77f0525d-7e6b-4795-bf9d-2111b9191174)

**Comment by 4IceG** [comment]
You can add a lot of data, but I don't need all of it. I have a slightly different vision of the 3ginfo package.
