### ISSUE TITLE
EM7455 data missing (with a fix)

### ISSUE THREAD

**Issue by jfrogg** [4IceG/luci-app-3ginfo-lite#50]
For whatever reason the support file for the original or **_generic_** EM7455 (1199:9071) is missing some code that is present in the Dell branded version of the same model (413c:81b6).
As a result, SIM information is not available as well as the modem model and firmware version.
Fixed by borrowing some code from  `/usr/share/3ginfo-lite/modem/413c81b6`.
[11999071.zip](https://github.com/4IceG/luci-app-3ginfo-lite/files/12708299/11999071.zip)

**Comment by 4IceG** [comment]
Hi @jfrogg  ,
Ok.. Thanks, I will add this fix in the next package update.
