### ISSUE TITLE
Cell Information 

### ISSUE THREAD

**Issue by lynxnexy** [4IceG/luci-app-3ginfo-lite#6]
LAC: - not showing
![IMG_20220228_215649](https://user-images.githubusercontent.com/81577496/156004902-1022e475-ca03-4053-bac4-59e7f3e62039.jpg)

**Comment by 4IceG** [comment]
Hi,
In Hi Link mode not all data will / must be completed and this is not a
bug. It all depends on the modem firmware.

pon., 28 lut 2022, 15:57 użytkownik lynxnexy ***@***.***>
napisał:
