### ISSUE TITLE
add support to SimCom SIM7906 lte module

### ISSUE THREAD

**Issue by aivavia** [4IceG/luci-app-3ginfo-lite#61]
Hello there, mr Rafal. I beg you add full support of sim7906 lte module (VID:1e0e) PID can be 9000,9001 (QMI) or 9003 (MBIM) , because the signal meters contains only CSQ.
here are the response of AT commands, that shows full statistic of LTE signal quality:

```
AT+CPSI?
+CPSI: LTE,Online,250-02,0x0EF8,22060,58,EUTRAN-BAND3,1725,3,3,-108,-889,-614,19

OK
AT+CMGRMI=4
+CMGRMI: Main_Info,4,1,1,0,2,52709,0,2,11

+CMGRMI: Serving_Cell,1725,250,02,3832,2,22060,3,3,3,19,58,-107,-890,-625,0

+CMGRMI: CA_Scell,0,0,0,0,0,0,0,0,0,0,0,0

+CMGRMI: LTE_Intra,1,1725,58,1

+CMGRMI: LTE_Intra_Cell1,58,-107,-890,-625,0

+CMGRMI: LTE_Inter,0,Freq1,0,0,0,0,0,Freq2,0,0,0,0,0

+CMGRMI: GSM_Info,0,Freq_Group1,0,0,0,0,0,Freq_Group2,0,0,0,0,0

+CMGRMI: WCDMA_Info,0,Freq1,0,0,0,0,0,Freq2,0,0,0,0,0

+CMGRMI: CDMA1x_Info,0,Freq1,0,0,0,Freq2,0,0,0

+CMGRMI: CDMAprpd_Info,0,Freq1,0,0,0,Freq2,0,0,0

+CMGRMI: CDrx_Cfg,1,2,80,8,40,21,1,20,1

+CMGRMI: Cqi_Cfg,1,1,4,0,1,1,14,58,0,0,1,161,0,0,0,0

+CMGRMI: Ant_Cfg,4,0x000000000000003F,0,0

+CMGRMI: Idle_Drx_Cfg,640,2,135

OK
```

**Comment by 4IceG** [comment]
Hi @aivavia 

Check if this version [luci-app-3ginfo-lite_1.0.65-20240302_all.zip](https://github.com/4IceG/luci-app-3ginfo-lite/files/14469198/luci-app-3ginfo-lite_1.0.65-20240302_all.zip) of the package shows more data.

**Comment by aivavia** [comment]
Sorry to say, but nope. Nothing of needed info is displayed. Only CSQ. No RSRP, RSSI, SINR meters at all :(
![Снимок экрана 2024-03-03 094824](https://github.com/4IceG/luci-app-3ginfo-lite/assets/111590310/f0bfa285-09fc-4dee-9c73-74f0ff3f52bc)

**Comment by 4IceG** [comment]
OK, I added all modem variants to the package. Now we need to see why the script is not reading the data correctly.

@aivavia Show result of the command `sh -x /usr/share/3ginfo-lite/3ginfo.sh`

**Comment by aivavia** [comment]
Here you are, please.
[3ginfo.txt](https://github.com/4IceG/luci-app-3ginfo-lite/files/14477625/3ginfo.txt)

**Comment by 4IceG** [comment]
Ok thanks,

@aivavia Check if this version [luci-app-3ginfo-lite_1.0.65-20240304_all.zip](https://github.com/4IceG/luci-app-3ginfo-lite/files/14480079/luci-app-3ginfo-lite_1.0.65-20240304_all.zip) of package shows more data.

**Comment by aivavia** [comment]
oh no, smth is totally broken now 
![Снимок экрана 2024-03-05 094709](https://github.com/4IceG/luci-app-3ginfo-lite/assets/111590310/d784c49f-22b0-4ccf-b0e0-521802e12e5b)

**Comment by 4IceG** [comment]
Ok, we are looking again.

@aivavia Show result of the command `sh -x /usr/share/3ginfo-lite/3ginfo.sh`

**Comment by aivavia** [comment]
[3ginfo_new.txt](https://github.com/4IceG/luci-app-3ginfo-lite/files/14490646/3ginfo_new.txt)
here you are

**Comment by aivavia** [comment]
You are the BEST! all meters are working now flawessly!
![Снимок экрана 2024-03-06 085935](https://github.com/4IceG/luci-app-3ginfo-lite/assets/111590310/2d0c2a96-488d-4121-9e71-c0154cf4c07a)
