### ISSUE TITLE
Cannot compile as addon feed on OpenWrt latest snapshot

### ISSUE THREAD

**Issue by stich86** [4IceG/luci-app-3ginfo-lite#67]
Hi @4IceG,

i'm trying to add your tools on my custom build for BPI-R3-Mini, but when add your plugin, I got this error during compile about `chat` package:

```
Collected errors:
 * check_data_file_clashes: Package busybox wants to install file /home/lynx/5G_Router/Banana-BPI-R3-Mini/openwrt/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/usr/sbin/chat
	But that file is already provided by package  * chat
 * opkg_install_cmd: Cannot install package busybox.
```

Your plugin select automatically `chat` package, and `busybox` has `chat` binary disabled, but looks like during the build it still tries to override. Any suggestion? Are you able to compile latest snapshot adding your feed?

Thanks in advance!

**Comment by 4IceG** [comment]
Hey @stich86 , 
The last time I compiled, I had no problems with my packages.

This is your compilation :), if the dependencies conflict with each other, remove the chat package from the Makefile.

**Comment by stich86** [comment]
it was local problem on the build, solved after a make clean ;)
