### ISSUE TITLE
Connection statistics not working 

### ISSUE THREAD

**Issue by lynxnexy** [4IceG/luci-app-3ginfo-lite#7]
![1](https://user-images.githubusercontent.com/81577496/164415481-535f992c-1ac9-4d64-99ec-e55af68aac47.jpg)

**Comment by lynxnexy** [comment]
![Screenshot_2022-04-21-16-40-22-717_com android chrome](https://user-images.githubusercontent.com/81577496/164427405-2debb00c-e716-475e-aab3-4f0789b147de.jpg)
![Screenshot_2022-04-21-16-40-41-054_com android chrome](https://user-images.githubusercontent.com/81577496/164427434-6b1857aa-0483-48b7-a2fa-11fc1fae0343.jpg)

**Comment by 4IceG** [comment]
You should set "wan" instead of eth1.

czw., 21 kwi 2022, 11:41 użytkownik lynxnexy ***@***.***>
napisał:
