### ISSUE TITLE
No Operator Name in LT4220 (QMI)

### ISSUE THREAD

**Issue by bulzed** [4IceG/luci-app-3ginfo-lite#71]
There is no operator name for my modem HP LT4220 (QMI mode). I already ran 3ginfo.sh manually still no result in "operator_name" line, it's only prints "operator_mcc", "operator_mnc", "location" etc. So there is no operator name in luci neither, eventhough it shows "Location" instead of my provider under signal bar in luci.
Kindly fix it, please . . .

**Comment by 4IceG** [comment]
Hi @bulzed ,
Replace the 3ginfo.sh file (\usr\share\3ginfo-lite) and check if the error disappears.
[3ginfo.zip](https://github.com/4IceG/luci-app-3ginfo-lite/files/15042493/3ginfo.zip)

**Comment by bulzed** [comment]
thanks a lot, dev...
let me try . . .

    On Friday, April 19, 2024 at 10:27:37 PM GMT+7, Rafał Wabik ***@***.***> wrote:  
 
 


Hi @bulzed ,
Replace the 3ginfo.sh file (\usr\share\3ginfo-lite) and check if the error disappears.
3ginfo.zip

**Comment by bulzed** [comment]
thanks dev, now everything works normally . . . 
🥂

**Comment by Inlifeuser** [comment]
I have the same problem with Huawei E3372 in NCM mode, and replacing 3ginfo.sh helped me too.
