### ISSUE TITLE
Problem z modemem Huawei e5786

### ISSUE THREAD

**Issue by lukjod** [4IceG/luci-app-3ginfo-lite#72]
Po aktualizacji nie pokazuje statystyki polaczenia i wywala niebieski ekran zlych ustawien na gorze. We wczesniej wersji bylo ok
![Zrzut ekranu 2024-04-21 141452](https://github.com/4IceG/luci-app-3ginfo-lite/assets/1781446/df201cdf-3505-403b-82e7-0efeb4bde568)

**Comment by 4IceG** [comment]
Cześć @lukjod ,
Podmień sobie plik 3ginfo.sh [3ginfo.zip](https://github.com/4IceG/luci-app-3ginfo-lite/files/15052010/3ginfo.zip) (\usr\share\3ginfo-lite) i daj znać czy będzie OK. 

Edytowałem na szybko na Windowsie, więc pewnie trzeba będzie zmienić aby skrypt był wykonywalny.

**Comment by lukjod** [comment]
Dzieki juz dziala
