### ISSUE TITLE
No operator info on Fibocom FM350-GL at 1.0.67-20240421 version

### ISSUE THREAD

**Issue by prusa-dev** [4IceG/luci-app-3ginfo-lite#73]
Hi, @4IceG 
Operator's info disappeared in version 1.0.67-20240421.
![image](https://github.com/4IceG/luci-app-3ginfo-lite/assets/161749114/85900569-fffc-4c73-ba01-304e583623e6)

In my [MR](https://github.com/4IceG/luci-app-3ginfo-lite/pull/70/files#diff-bfb9df31e7c9175e9d10b5dca27891b6c20b9997ed0df263b257f34796d5067aR278), I have changed the `AT+COPS` command response parsing according to how the modem responds. This change is suitable for all modems.
But in version 1.0.67-20240421, I see that you have canceled this change. Therefore, the operator's name disappeared.

Here is FM350-GL response:
```
AT+COPS=3,0;+COPS?;+COPS=3,2;+COPS?
+COPS:0,0,"MTS RUS",7

+COPS:0,2,"25001",7

OK
```

As you can see, there is no space between `+COPS:` and `0`. Therefore, I changed the regex and added `\s?`

**Comment by 4IceG** [comment]
Hi @prusa-dev ,
Ok, I understand that my changes overwrote your modifications. I'll fix it later today.

**Comment by 4IceG** [comment]
It should be OK now.
