### ISSUE TITLE
Undefined connection statistics in LuCI

### ISSUE THREAD

**Issue by Inlifeuser** [4IceG/luci-app-3ginfo-lite#77]
This only appears in last version 1.0.70 (after upgrade from 1.0.69). In previous version 1.0.69 (after downgrade) statistics are displayed correctly.
![1 0 70 conn stat](https://github.com/4IceG/luci-app-3ginfo-lite/assets/25416459/c38726db-a288-464d-9371-0cb943d4c0b4)

I also noticed that the format for displaying these statistics in JSON has changed, and it seems that changes to the web interface were missed.

1.0.70:
![1 0 70 json](https://github.com/4IceG/luci-app-3ginfo-lite/assets/25416459/85690a0e-358b-4301-8218-fc9fd6545ffb)

1.0.69:
![1 0 69 json](https://github.com/4IceG/luci-app-3ginfo-lite/assets/25416459/1ae68a63-9711-4f3e-8995-10598da90d78)

**Comment by 4IceG** [comment]
Hi @Inlifeuser ,
Clear your browser cache.

**Comment by Inlifeuser** [comment]
Before this I also tried to reboot OpenWrt, and it did not help. After clearing the browser cache, statistics are now displayed correctly. Thanks!
