### ISSUE TITLE
the package don't work properly on web pages

### ISSUE THREAD

**Issue by yyllxxhh** [4IceG/luci-app-3ginfo-lite#80]
I followed the instructions in the README.md to compile an IPK installer, and I installed it on my system using the OPKG command. However, there's no MODEM option in the status bar of the web interface, even though the SIM card is working fine.

Details:
- OpenWrt Version: LEAN LEDE
- Linux Kernel Version: 4.9.84

Any ideas on what might be going wrong? Thanks!

**Comment by 4IceG** [comment]
Hi @yyllxxhh , if there is no modem menu, you may need:
- click somewhere else in the menu 
- logging out of the router 
- clearing the browser cache

**Comment by obsy** [comment]
- use current version of luci...

**Comment by yyllxxhh** [comment]
after updating the luci version, the modem menu is now working properly.
